### ISSUE TITLE
Revisit entry.effects.spec.ts

### ISSUE THREAD

**Issue by enriquezrene** [ioet/time-tracker-ui#433]
The implemented test 
```
it('When the service returns a value, then RESTART_ENTRY_SUCCESS should be triggered', () => {
```

it's causing random issues. This seems a flaky test that needs to be revisited. Here is the error that sometimes appears in the console (commented test in the meantime):

```
hrome 83.0.4103.116 (Mac OS 10.13.6) ERROR
  An error was thrown in afterAll
  TypeError: Cannot read property 'id' of undefined
      at <Jasmine>
      at MergeMapSubscriber.project (http://localhost:9876/_karma_webpack_/main.js:48431:51)
      at MergeMapSubscriber._tryNext (http://localhost:9876/_karma_webpack_/node_modules/rxjs/_esm2015/internal/operators/mergeMap.js:46:1)
      at MergeMapSubscriber._next (http://localhost:9876/_karma_webpack_/node_modules/rxjs/_esm2015/internal/operators/mergeMap.js:36:1)
      at MergeMapSubscriber.next (http://localhost:9876/_karma_webpack_/node_modules/rxjs/_esm2015/internal/Subscriber.js:49:1)
      at MapSubscriber._next (http://localhost:9876/_karma_webpack_/node_modules/rxjs/_esm2015/internal/operators/map.js:35:1)
      at MapSubscriber.next (http://localhost:9876/_karma_webpack_/node_modules/rxjs/_esm2015/internal/Subscriber.js:49:1)
      at FilterSubscriber._next (http://localhost:9876/_karma_webpack_/node_modules/rxjs/_esm2015/internal/operators/filter.js:33:1)
      at FilterSubscriber.next (http://localhost:9876/_karma_webpack_/node_modules/rxjs/_esm2015/internal/Subscriber.js:49:1)
      at Observable._subscribe (http://localhost:9876/_karma_webpack_/node_modules/rxjs/_esm2015/internal/util/subscribeToArray.js:3:1)
      at Observable._trySubscribe (http://localhost:9876/_karma_webpack_/node_modules/rxjs/_esm2015/internal/Observable.js:42:1)
Chrome 83.0.4103.116 (Mac OS 10.13.6) ERROR
  An error was thrown in afterAll
  TypeError: Cannot read property 'id' of undefined
      at <Jasmine>
      at MergeMapSubscriber.project (http://localhost:9876/_karma_webpack_/main.js:48431:51)
      at MergeMapSubscriber._tryNext (http://localhost:9876/_karma_webpack_/node_modules/rxjs/_esm2015/internal/operators/mergeMap.js:46:1)
      at MergeMapSubscriber._next (http://localhost:9876/_karma_webpack_/node_modules/rxjs/_esm2015/internal/operators/mergeMap.js:36:1)
      at MergeMapSubscriber.next (http://localhost:9876/_karma_webpack_/node_modules/rxjs/_esm2015/internal/Subscriber.js:49:1)
      at MapSubscriber._next (http://localhost:9876/_karma_webpack_/node_modules/rxjs/_esm2015/internal/operators/map.js:35:1)
      at MapSubscriber.next (http://localhost:9876/_karma_webpack_/node_modules/rxjs/_esm2015/internal/Subscriber.js:49:1)
      at FilterSubscriber._next (http://localhost:9876/_karma_webpack_/node_modules/rxjs/_esm2015/internal/operators/filter.js:33:1)
      at FilterSubscriber.next (http://localhost:9876/_karma_webpack_/node_modules/rxjs/_esm2015/internal/Subscriber.js:49:1)
      at Observable._subscribe (http://localhost:9876/_karma_webpack_/node_modules/rxjs/_esm2015/internal/util/subscribeToArray.js:3:1)
      at Observable._trySubscribe (http://localhost:9876/_karma_webpack_/node_modules/rxjs/_esm2015/internal/Observable.js:42:1)
```

**Comment by enriquezrene** [comment]
This issue seems to not be happening any more, closing this ticket with no implementation needed
